# Generated by Django 3.0.8 on 2020-08-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200808_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='clk',
            field=models.TextField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='clk1',
            field=models.TextField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
