# Generated by Django 3.0.8 on 2020-08-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200809_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='clk1',
            new_name='Gender',
        ),
    ]
