# Generated by Django 3.0.8 on 2020-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200809_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Phone',
            field=models.CharField(max_length=30),
        ),
    ]
